
const FETCH_RECENTLY_RATED_MOVIES_ACTION = 'FETCH_RECENTLY_RATED_MOVIES_ACTION';
const FETCH_RECENTLY_RATED_MOVIES_SUCCESS = 'FETCH_RECENTLY_RATED_MOVIES_SUCCESS';

export default {
    FETCH_RECENTLY_RATED_MOVIES_ACTION,
    FETCH_RECENTLY_RATED_MOVIES_SUCCESS
}